[project]
name = "digital-art-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "rich>=14.2.0",
]
